[package]
name = "termion-tokio"
version = "0.1.0"
authors = ["Kayo Phoenix <kayo@illumium.org>"]

[dependencies]
bytes = "0.6.0"
futures = "0.3.8"
tokio = "0.3.0"
termion = "1"
tokio-util = { version = "0.5.1", features = ["codec"] }
